Let ueventd do the coldplug
ubports/lxc-android-config pull request #26
Opened 2019-08-26 08:52 UTC by peat-psuwit

This commit makes udev start before Android container and let ueventd do
the coldplug. This prevent double coldboot/coldplug and make camera
works on FP2 with Halium 7.1 port.

On FP2 with Halium 7.1, mm-qcamera-daemon happens to start in the
container at approx. the same time with udevtrigger job. As part of
daemon's startup, it talks to some kernel interface to init camera
sensor's v4l-subdev's and expect them to appear shortly after that. But
with overwhelming amount of uevents generate by udevtrigger, Android's
ueventd takes some time until it can create such device nodes. This make
the daemon fails to find the device node and assume that initialisation
fails. By preventing double coldboot/coldplug, ueventd will be able to
create such device nodes in time, making the camera works.

2019-08-26 20:48 UTC, fredldotme commented
LGTM

2019-08-26 20:51 UTC, fredldotme submitted a review, later dismissed

2019-08-28 14:43 UTC, UniversalSuperBox requested changes
We must receive a test from every supported device for this to be merged. *All* hardware must be tested for its functionality equal to before this change is installed.

Optionally, we'd like these tests on edge and devel

* [x] Meizu MX4
* [x] Oneplus One
* [x] Fairphone 2
* [x] Nexus 5
* [x] BQ M10 FHD
* [x] BQ M10 HD
* [x] BQ E4.5 
* [x] BQ E5
* [ ] Meizu Pro 5
* [x] Nexus 4
* [x] Nexus 7 2013 WiFi (no audio when recording video, may not be a regression)
* [x] Nexus 7 2013 LTE
* [x] Moto G 2014 (if we hear back from @walidham)

2019-08-28 16:08 UTC, walidham commented
I will test it this night for Moto G 2014, before camera doesn't work

2019-09-04 18:25 UTC, UniversalSuperBox commented
@walidham, did it work?

2019-09-04 21:18 UTC, walidham commented
fresh install
Camera crash got this error
`Sep  4 20:57:45 ubuntu-phablet dbus[3258]: apparmor="DENIED" operation="dbus_method_call"  bus="session" path="/com/canonical/libertine/Service/Operations" interface="com.canonical.libertine.Service.Operations" member="list" mask="send" name="com.canonical.libertine.Service" pid=23495 label="com.ubuntu.camera_camera_3.1.0" peer_pid=6786 peer_label="unconfined"
`


Change this files
```
/etc/init/lxc-android-config.conf
/etc/init/udev.override
```

add new file `/etc/init/udevtrigger.override`

reboot
now flash work but still no image or video
maybe its kernel pb, i got this error
```
[    1.534417]    1.534417,0] msm_camera_cci_i2c_read: line 56 rc = -22
[    1.536836]    1.536836,0] msm_camera_cci_i2c_read: line 56 rc = -22
[    1.539987]    1.539987,0] msm_camera_cci_i2c_read: line 56 rc = -22
[    1.572238]    1.572238,0] qcom,imx132: probe of 32.qcom,camera failed with error -22
[   87.874055]   87.874055,2] msm_camera_request_gpio_table:581 gpio 26:CAMIF_MCLK request fails
[  133.703209]  133.703209,1] msm_camera_request_gpio_table:581 gpio 26:CAMIF_MCLK request fails
```

2019-09-04 21:28 UTC, UniversalSuperBox commented
Well, we really need to check if anything is newly *broken* with these changes. If not, it's good enough.

2019-09-04 21:33 UTC, walidham commented
no newly broken things

2019-09-04 21:55 UTC, UniversalSuperBox commented
Awesome!

@peat-psuwit, it appears that this change causes us to lose a race on the Nexus 5. After applying the change, I am no longer able to connect to Wi-Fi. Something uses 100% of the CPU related to Wi-Fi hardware, like NetworkManger or wl_event_handle. Just like this, but it happens every time the device reboots rather than just sometimes: https://github.com/ubports/ubuntu-touch/issues/304

2019-09-04 22:39 UTC, mariogrip commented
> Awesome!
> 
> @peat-psuwit, it appears that this change causes us to lose a race on the Nexus 5. After applying the change, I am no longer able to connect to Wi-Fi. Something uses 100% of the CPU related to Wi-Fi hardware, like NetworkManger or wl_event_handle. Just like this, but it happens every time the device reboots rather than just sometimes: [ubports/ubuntu-touch#304](https://github.com/ubports/ubuntu-touch/issues/304)

You might want to try reverting this: https://github.com/ubports/android_device_lge_hammerhead/commit/674bae3113abce68819baa42a29656b194f27aa1#diff-1ebd87e6a3235c14649fa361aed9957e

2019-09-25 16:01 UTC, NeoTheThird commented
All hardware working on M10 HD.

2019-09-27 00:32 UTC, UniversalSuperBox commented
The issue with the Nexus 5 has been fixed.

However, we've found that this causes Wi-Fi to be switched off on boot on the BQ E4.5, no matter the state of the chipset before rebooting.

2019-11-05 20:58 UTC, doniks commented
No regressions on Nexus 7 gsm, "deb".

I compared devel image (20191105-20722) against adding `dpkg --install ....deb`. wifi, gsm (don't have a sim to test, but I can scan for carriers), gps, led, rotation, brightness, sound, youtube still work. camera and bluetooth still do not work, but that never worked as far as I remember. Video playback doesn't seem to work in latest devel, but that's unaffected by this lxc-android-config patch.

2020-01-05 19:30 UTC, peat-psuwit commented
So, people with BQ E4.5, please try installing this version of URfkill from https://github.com/ubports/urfkill-packaging/pull/3 along side with this PR. This fixes a race condition making it unable to enable Wi-Fi at boot. [`urfkill_0.7.0+ubports+0~20200105190143.1~1.gbp696ec1_armhf.deb`](https://ci.ubports.com/job/urfkill-packaging/job/PR-3/1/artifact/urfkill_0.7.0+ubports+0~20200105190143.1~1.gbp696ec1_armhf.deb)

2020-05-12 17:48 UTC, UniversalSuperBox commented
This PR is blocked by https://github.com/ubports/ubuntu-touch/issues/1396. It is potentially possible that other devices are also slowed down by this change and we could diagnose the issue with one of them.

2020-07-01 19:44 UTC, rubencarneiro commented
Meizu pro 5 booted fine. On stable channel.

2020-07-02 00:21 UTC, UniversalSuperBox commented
With that, this is ready for merge for devel, but only after an update has been released after this message. This will allow us to have a good testing base to see if something was due to the PulseAudio update or this one.

2020-07-02 13:39 UTC, UniversalSuperBox approved these changes

2020-07-02 13:39 UTC, merged

2020-09-06 15:17 UTC, jezek commented
There is a call for testing. How do we test this, please?

2020-09-07 10:10 UTC, peat-psuwit commented
If the device boots in a timely manner, then it should work. You shouldn't notice any regression.

2020-09-07 16:06 UTC, jezek commented
Device: FP2
Image: 2020-W36

Boot time from power off until homescreen (sim inserted, wifi on, no pin or passphrase required): cca 1 minute.
I could swear, it was 30 seconds 3 years ago... but my memory is not, what it used to be and didn't make any measurements back then. :wink: