Don't change rfkill's group to android_input
ubports/lxc-android-config pull request #36
Opened 2020-08-13 21:15 UTC by UniversalSuperBox

The /dev/rfkill device was set to the android_input group in a commit before the current git repository can even remember. We later ensured that it happened by setting the group even later, in  3e1871d. But the correct solution is actually to add phablet to the netdev group, which the rfkill device is owned by on a Debian system, and drop this rule.

This commit requires all-device testing, and is absolutely not valid for merge before the OTA-13 release.

2020-10-07 18:34 UTC, dobey approved these changes

2020-10-07 18:43 UTC, UniversalSuperBox commented
It does not appear that `phablet` is a member of `netdev` yet, so I appear to have forgotten something. I don't think this is safe to merge until phablet is a member of netdev.

2020-10-09 20:21 UTC, dobey requested changes
Just setting this to request changes to have the big red flag there in case someone thinks it's a good idea to merge it. We need to solve the issue of phablet not being in netdev group first.

2021-01-12 15:33 UTC, UniversalSuperBox commented
lxc-android-config has moved to GitLab, this PR may be reopened there: https://gitlab.com/ubports/core/hybris-support/lxc-android-config

2021-01-12 15:33 UTC, closed without merging